apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-svc-proxy
  namespace: default
  labels:
    app: http-svc

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: http-svc-proxy
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - namespaces
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: http-svc-proxy
  namespace: default
  labels:
    app: http-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: http-svc-proxy
subjects:
  - kind: ServiceAccount
    name: http-svc-proxy
    namespace: default

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: http-svc
  name: http-svc-proxy
  namespace: default
spec:
  selector:
    matchLabels:
      app: http-svc-proxy
  template:
    metadata:
      labels:
        app: http-svc-proxy
        kind: horus-proxy
    spec:
      serviceAccountName: http-svc-proxy
      containers:
      - env:
        - name: PROXY_NAMESPACE
          value: default
        - name: PROXY_SERVICE
          value: http-svc
        image: aledbf/horus-proxy:dev
        imagePullPolicy: Always
        name: http-svc-proxy
